markdown: kramdown

title: "World Bank Open Government Data Toolkit"
description: "The Open Government Data Toolkit is designed to help governments, Bank staff and users understand the basic precepts of Open Data, then get \"up to speed\" in planning and implementing an open government data program, while avoiding common pitfalls."
